name: Build EXE

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchomienie w każdą niedzielę o północy UTC

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Zastąp odpowiednią wersją Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-exe
          path: dist/main.exe
